#!/usr/bin/env bash
#
# rollback.sh — v1: code-only single-PR revert path for IFleet.
#
#   bash deploy/rollback.sh            # interactive: pick a commit from the
#                                      # last 5 first-parent commits on main
#   bash deploy/rollback.sh <sha>      # non-interactive: revert that SHA
#   DRY_RUN=1 bash deploy/rollback.sh  # show planned actions, no changes
#
# What it does:
#   1. Lists the last 5 first-parent commits on origin/main.
#   2. Prompts (or accepts argv) for the SHA to revert.
#   3. Creates a new branch off latest main and runs `git revert <sha>`.
#   4. Pushes the branch and opens a PR via `gh` so branch protection still
#      applies. Does NOT merge directly.
#   5. Optionally reloads PM2 services if the revert touches ecosystem.config.cjs
#      or src/ — toggled by RELOAD_PM2=1 and requires SSH to the VPS.
#   6. Verifies https://control.weautomatehq.cloud/healthz returns 200 after
#      reload.
#   7. Appends a one-line audit record to /var/log/pm2/ifleet-rollback.log
#      (or ./ifleet-rollback.log locally if /var/log/pm2 is not writable).
#
# Out of scope (v1):
#   - Cross-host orchestration (assumes you run this on the laptop or VPS).
#   - Database rollback. Supabase / Postgres migration reverts are MANUAL —
#     follow `docs/runbooks/secrets.md` and the Supabase dashboard.
#   - Multi-commit / time-window rollback. v1 reverts a single SHA per run.
#   - Self-PRs (`label:ifleet:self`) — those have their own rollback path in
#     `docs/elevation/operating-standard.md §Rollback path` and require a PM2
#     env reload against a prior git tag.

set -euo pipefail

REPO_REMOTE="${IFLEET_REPO_REMOTE:-origin}"
MAIN_BRANCH="${IFLEET_MAIN_BRANCH:-main}"
VPS="${IFLEET_VPS:-root@187.124.77.142}"
HEALTH_URL="${IFLEET_HEALTH_URL:-https://control.weautomatehq.cloud/healthz}"
DRY_RUN="${DRY_RUN:-0}"
RELOAD_PM2="${RELOAD_PM2:-0}"
AUDIT_LOG_REMOTE="/var/log/pm2/ifleet-rollback.log"
AUDIT_LOG_LOCAL="./ifleet-rollback.log"

log()  { printf '\n\033[1;33m[rollback]\033[0m %s\n' "$*"; }
fail() { printf '\n\033[1;31m[rollback]\033[0m %s\n' "$*" >&2; exit 1; }
run()  {
  if [[ "$DRY_RUN" == "1" ]]; then
    printf '  DRY-RUN: %s\n' "$*"
  else
    "$@"
  fi
}

# ---- preflight --------------------------------------------------------------
command -v git >/dev/null 2>&1 || fail "git is required"
command -v gh  >/dev/null 2>&1 || fail "gh is required (https://cli.github.com/)"

git rev-parse --is-inside-work-tree >/dev/null 2>&1 \
  || fail "must be run from inside an IFleet git checkout"

log "Fetching $REPO_REMOTE/$MAIN_BRANCH"
git fetch "$REPO_REMOTE" "$MAIN_BRANCH"

# ---- pick the SHA -----------------------------------------------------------
SHA="${1:-}"

if [[ -z "$SHA" ]]; then
  log "Last 5 first-parent commits on $REPO_REMOTE/$MAIN_BRANCH:"
  git log --first-parent "$REPO_REMOTE/$MAIN_BRANCH" -5 \
    --format='  %h  %ad  %s' --date=iso-strict
  echo
  printf 'Revert which SHA (short or full)? '
  read -r SHA
  [[ -z "$SHA" ]] && fail "no SHA provided"
fi

git rev-parse --verify "$SHA^{commit}" >/dev/null 2>&1 \
  || fail "SHA $SHA does not resolve to a commit"

FULL_SHA=$(git rev-parse "$SHA^{commit}")
SHORT_SHA=$(git rev-parse --short "$FULL_SHA")
COMMIT_SUBJECT=$(git log -1 --format='%s' "$FULL_SHA")

log "Will revert: $SHORT_SHA  $COMMIT_SUBJECT"

# ---- detect scope -----------------------------------------------------------
CHANGED=$(git show --name-only --format= "$FULL_SHA" | sed '/^$/d')
readarray -t CHANGED_FILES <<<"$CHANGED"
TOUCHES_RUNTIME=0
if grep -qE '^(src/|ecosystem\.config\.cjs$)' <<<"$CHANGED"; then
  TOUCHES_RUNTIME=1
fi
log "Files touched by $SHORT_SHA:"
printf '  %s\n' "${CHANGED_FILES[@]}"
log "Touches runtime (src/ or ecosystem): $TOUCHES_RUNTIME"

# ---- branch + revert + push -------------------------------------------------
TS=$(date +%Y%m%d-%H%M%S)
BRANCH="revert/${SHORT_SHA}-${TS}"

log "Creating branch $BRANCH off $REPO_REMOTE/$MAIN_BRANCH"
run git checkout -b "$BRANCH" "$REPO_REMOTE/$MAIN_BRANCH"

log "Reverting $SHORT_SHA"
run git revert --no-edit "$FULL_SHA"

log "Pushing $BRANCH"
run git push -u "$REPO_REMOTE" "$BRANCH"

# ---- open PR ----------------------------------------------------------------
PR_BODY=$(cat <<EOF
Automated revert of $SHORT_SHA — \`$COMMIT_SUBJECT\`.

Generated by \`deploy/rollback.sh\` per the operating standard rollback path.

## What this reverts
- \`$FULL_SHA\` — $COMMIT_SUBJECT

## Files touched by the original commit
$(printf -- '- \`%s\`\n' "${CHANGED_FILES[@]}")

## Test plan
- [ ] CI green on this revert
- [ ] Manual: \`curl $HEALTH_URL\` returns 200 after merge + PM2 reload
- [ ] Confirm the reported failure that triggered the rollback no longer reproduces

Audit log entry appended to \`$AUDIT_LOG_REMOTE\` (or \`$AUDIT_LOG_LOCAL\` if local).
EOF
)

log "Opening draft PR via gh"
if [[ "$DRY_RUN" == "1" ]]; then
  printf '  DRY-RUN: gh pr create --draft --title "revert: %s" --body <generated>\n' "$COMMIT_SUBJECT"
  PR_URL="(dry-run; no PR opened)"
else
  PR_URL=$(gh pr create \
    --draft \
    --base "$MAIN_BRANCH" \
    --head "$BRANCH" \
    --title "revert: $COMMIT_SUBJECT" \
    --body "$PR_BODY")
  log "PR opened: $PR_URL"
fi

# ---- optional PM2 reload ----------------------------------------------------
if [[ "$TOUCHES_RUNTIME" == "1" && "$RELOAD_PM2" == "1" ]]; then
  log "Runtime touched + RELOAD_PM2=1 — reloading control-plane + ifleet on $VPS"
  if [[ "$DRY_RUN" == "1" ]]; then
    printf '  DRY-RUN: ssh %s pm2 reload control-plane --update-env && pm2 reload ifleet --update-env && pm2 save\n' "$VPS"
  else
    ssh "$VPS" 'set -a; . /etc/environment; set +a; pm2 reload control-plane --update-env && pm2 reload ifleet --update-env && pm2 save'
  fi
else
  log "Skipping PM2 reload (runtime touched=$TOUCHES_RUNTIME, RELOAD_PM2=$RELOAD_PM2). Reload happens after the revert PR merges and main is redeployed."
fi

# ---- healthz verify ---------------------------------------------------------
if [[ "$DRY_RUN" != "1" && "$RELOAD_PM2" == "1" ]]; then
  log "Health check: $HEALTH_URL"
  if ! curl -fsS --max-time 10 "$HEALTH_URL" >/dev/null; then
    fail "Health check failed after PM2 reload. Investigate immediately: ssh $VPS pm2 logs control-plane --lines 100"
  fi
  log "Healthz OK."
fi

# ---- audit log --------------------------------------------------------------
LINE="$(date -u +%Y-%m-%dT%H:%M:%SZ) revert sha=$FULL_SHA branch=$BRANCH pr=$PR_URL runtime=$TOUCHES_RUNTIME reload=$RELOAD_PM2 dry_run=$DRY_RUN by=$(git config user.email)"

if [[ "$DRY_RUN" == "1" ]]; then
  printf '  DRY-RUN audit line: %s\n' "$LINE"
elif ssh -o BatchMode=yes -o ConnectTimeout=5 "$VPS" "test -w \"$(dirname "$AUDIT_LOG_REMOTE")\"" 2>/dev/null; then
  ssh "$VPS" "printf '%s\n' \"$LINE\" >> $AUDIT_LOG_REMOTE"
  log "Audit logged to $VPS:$AUDIT_LOG_REMOTE"
else
  printf '%s\n' "$LINE" >> "$AUDIT_LOG_LOCAL"
  log "Audit logged to $AUDIT_LOG_LOCAL (VPS log unavailable)"
fi

log "Done. Review the PR, get human approval, merge. If the revert is urgent and the PR is green, an admin merge through branch protection is acceptable per docs/elevation/operating-standard.md §Rollback path."
